### ISSUE TITLE
Invalid table column length when using hyperlinks

### ISSUE THREAD

**Issue by IonBazan** [symfony-cli/terminal#4]
Not sure if it is caused by this repository so please feel free to move or close this issue if needed.

When running `symfony server:list`, the length of `Port` column doesn't match the content length:
<img width="407" alt="image" src="https://user-images.githubusercontent.com/1985514/176840564-75729e9c-6b48-4cf9-8923-1397c2f564c3.png">

This is working fine when running with `--no-ansi`:
<img width="407" alt="image" src="https://user-images.githubusercontent.com/1985514/176840636-555d9950-f725-40d6-91cd-7082f0b14c7c.png">

I believe it's caused by the length calculation including the `http:/127.0.0.1:8000` Terminal Hyperlink embedded in the table content. Special formatting characters (like colours and hyperlinks) should be ignored when determining the content length for tables.

**Comment by tucksaun** [comment]
The issue is caused by the fact that the package used to format tables only account for the whole string size (see https://github.com/symfony-cli/symfony-cli/issues/10 for more information).

IIRC there's nothing that `terminal` can do. The fix should be done in https://github.com/olekukonko/tablewriter (fix column size width computation) on in https://github.com/symfony-cli/symfony-cli (not use hyperlinks at all)

**Comment by tucksaun** [comment]
See https://github.com/olekukonko/tablewriter/pull/206 for the upstream fix.

Also, see https://github.com/symfony-cli/symfony-cli/pull/224 for a way to "inject" the fix in the vendor while waiting for an upstream merge if you directly use this library.

@fabpot I believe this issue can now be closed;

**Comment by IonBazan** [comment]
Amazing, thanks! Let's close it only after one of these PRs is merged.
